// Autogenerated by gen_tests.py and process_polyglot.py.
// Do not edit this file directly.
// The template for this file is located at:
// ../../gen_tests/template.go.tpl
package reql_tests

import (
"fmt"
	"testing"
	"time"

	"github.com/stretchr/testify/suite"
	r "gopkg.in/dancannon/gorethink.v2"
)

// These tests test the type of command
func TestDatumTypeofSuite(t *testing.T) {
	suite.Run(t, new(DatumTypeofSuite ))
}

type DatumTypeofSuite struct {
	suite.Suite

	session *r.Session
}

func (suite *DatumTypeofSuite) SetupTest() {
	fmt.Println("Setting up DatumTypeofSuite")
	// Use imports to prevent errors
	time.Now()

	session, err := r.Connect(r.ConnectOpts{
		Address: url,
	})
	suite.Require().NoError(err, "Error returned when connecting to server")
	suite.session = session

	r.DBDrop("test").Exec(suite.session)
	err = r.DBCreate("test").Exec(suite.session)
	suite.Require().NoError(err)
	err = r.DB("test").Wait().Exec(suite.session)
	suite.Require().NoError(err)

}

func (suite *DatumTypeofSuite) TearDownSuite() {
	fmt.Println("Tearing down DatumTypeofSuite")

	if suite.session != nil {
		r.DB("rethinkdb").Table("_debug_scratch").Delete().Exec(suite.session)
		r.DBDrop("test").Exec(suite.session)

		suite.session.Close()
	}
}

func (suite *DatumTypeofSuite) TestCases() {
	fmt.Println("Running DatumTypeofSuite: These tests test the type of command")



	{
		// datum/typeof.yaml line #5
		/* 'NULL' */
		var expected_ string = "NULL"
		/* r.expr(null).type_of() */

		fmt.Println("About to run line #5: r.Expr(nil).TypeOf()")

		runAndAssert(suite.Suite, expected_, r.Expr(nil).TypeOf(), suite.session, r.RunOpts{
			GroupFormat: "map",
			GeometryFormat: "raw",
		})
		fmt.Println("Finished running line #5")
	}

	{
		// datum/typeof.yaml line #9
		/* 'NULL' */
		var expected_ string = "NULL"
		/* r.type_of(null) */

		fmt.Println("About to run line #9: r.TypeOf(nil)")

		runAndAssert(suite.Suite, expected_, r.TypeOf(nil), suite.session, r.RunOpts{
			GroupFormat: "map",
			GeometryFormat: "raw",
		})
		fmt.Println("Finished running line #9")
	}
}
